# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jihaixiao's Blog
email: jihaixiao0804@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  记录我的java之旅，记住，一定不要让猪哥进来！！！
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jihaixiao
github_username:  jihaixiao8

# Build settings
markdown: kramdown
port: 5002
